name: Generate PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  textlint:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Lint
        run: |
          bun i
          bun textlint --fix resume.md
