name: TextLint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  textlint:
    name: TextLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bunx textlint --fix resume.md
