name: TextLint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  textlint:
    name: TextLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
          aqua_opts: ""

      - run: task lint
